sudo: required
services:
- docker
language: go
go:
- 1.7
script:
- make
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: R3b0KReEiRpIVqatvoBfgSE36rC0QDFoCFG1hM3KtjcVSQXiI1MJV+GVsXlC6SsRwoyle0vjy6IyE2rixOPx9Ztuwzpo39Hit7zZllZeElx2IzsQgkmR4FAPw/XOZVcZrVcg3ONQpgwtvup3oVy3fUhleXQ7meaXjybZJj61UY8Uo1x5caCLtzX+QncpO97SDhcar1ccnUwIhcgHufJpYAp47M53voLrJWd/Qq0zQxKZB/7+VarotlWMf/Pp5KSTvbW7SV9lHYJLIZL/bVvdU3Ynh05hrJtocUnIGVpXdgHqlgXKLCTqo9Qp/bCzj8sfCuvduGLba7HZQOb/tbl6uagWhHni1Nndvxwq1rZObn8WuhgLKiNW9Bh65a6zHZSWAkSLW01dCKscbvyZRY4dh5h/XYMwlcBr9umSNDKY3rfZHOZkdbWt8poafb5GP18kDmFz4uLiGyseiV/AJup0H69V+Gv2SOrlZwcBlR0P7K+p+vtdGDuDCF0bCDqWXmpPltczZbCEw8T35g1i8kIo3bxUn4j9qR0Zw4wjdbwRoa2h5pIiePFHwWDEPDYiYQxHmSO5NHkD1Ap2sBuKNwG0x1s4UQwiM5rLFNv95Lgm3sWy49qDEb5p/GwbH4+qzWp9Uc1xo7dJyfv0eTbm3x0mGdsmD2Hy77fT/Eofx2mEt3M=
  - secure: KuPCTlP4yRPh34Xxa/3eXjecLRcIMgVPPZStYAzun7X9wWyVJ0ffPY7YDtRIF8C0e4lobdy1lV5zCrJcUU+BwDQ+Ge83JakGqM/4FIm+ADYNARU7EZztUgf64BvA1WSTiVjbWrCkkR0Og1PHqeVuVJo4h0O3lAq/pscGx1LdWIN9YkBeJvrgcdRbIVVZDZSAKMGLrdLmy7KVBEny1/4wZ7+ailrxwdS8q22xSXgfjhG08CG4k5nP6Nc6y7v5jQH585AZhyd5zCq/imT766bT/aiOtGNAC7e8QYpD4V2BGTtJOkiUHA6YeUBK6f2qOlIo9k1HuQeBMMhHWaMLbrbsERh7dU0WawiWXN14KjpyE4N2KJC2ySL+dm6DxM9/hcrtuGyIHzxunjUuymHdApDY1XlcGBA6LK36BzZ0eDZik1KTuZlWWyvvx86tUQPLSskwfp4MZ+LzhNFAmRewxQ1bwwiYX3OHGD+aTxTPABPW2LA4GAyVtUlpY0rlRezinZ+xUI+WGODkkJxrOrkNgTNY2NbF5kcFmT1OsMl4/9f89WuTm2wlZpojcOTAz8icDxFAK6dRMkPu1ZER5+EDp2f5LbgjyIjqHfXq91JwkU3KEzsCWfDTJD8lI8iTpq6L99D1o8SuWAZuH/ud938YucebUAjyDUME6QVkGTu5Wjo1CII=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- export REPO=shapeshed/go-ci-cd
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
