language: go
go:
- 1.7
script:
- make
deploy:
  provider: heroku
  buildpack: https://github.com/kr/heroku-buildpack-go.git
  app: go-ci-cd
  api_key:
    secure: isFzpe/ByKgfkroxxgk03yMW9qPBDNmDCVmuog3RiWxRARYbelkEc79eajHW/T/WM8gqRYql11A8YaRWGcWWhxzOOtnjNqJyvQCkJRLYXMYsNE9AypQbrOIEeoRpKPMeE92hYvjES39lNLi0iWviKewt8dwG6U6fU8ayW8Ez2H8RRPQRomNUiaaem1VHHJTbZRZWXiODxc+l1pSJJWhiJVvqXqyN+Th0tFGBan2ur0mxrW5zfs/spKWo7W5O34ooe3BI84R2CBm+JMCsZ7mtqmiNHdygzjmiLo7gxsDyi10Mo4/JN9BS1nHrZuZo2eEaeufQd+kfNkGGo1NBIylAlwWZUtLyMGeo9gqygMTFRyiZxCxgyWYVM+09C/lZsaD6t5dG4ZS71R5BV9rDN5nL07L8T/lb3iiBNdLve/7jdtQpN57tqa3sFYSn7E3imD5pSE/SZjVfy2/xe9JLJTa2TVmqLScUXaSSASJciO6N8RKiGn5RcvZxiskWWZEfXDcE8/RwLDtKiccAm7XQVcJ+yneTnyJBDld+C0uZB3XzL8HAY09TRPeCIMHu65Q9w8bX4qMml7HVuOBWalGBE0OcdCUqlwHJ2NdR8w5AYNeXsFcQBXspCq5xjYXzbOvLcY8KTnmCf1DEjI5gsn6hs9U1gNcmjTEAp3PrL6AQa+PckB4=
