sudo: required
services:
- docker
language: go
go:
- 1.7
script:
- make
env:
  global:
  - secure: Nd3BgthDxiA0cl4PFoWl5pOHl4ZyrxX94PKhOq/4FiQIMdjgK2JSUcxxUPFq4dWufGbhb1eLPGmweAVYROv1Me1VQ7Zktbq3Gm85iuVrHhywYxACeMoIxxlJodhnd3x7Qj92UJDebmEKapBKZnn6vWpPoS2KC3w1p/HfQPX+2Or0puNDvT0brzxuaaSXw+GxB/sr3pdNhLSwOvY6+Gmjc/hsYqNnDivB+6WBcc+SrHhwbhjsH5rj06DDRPGruNMxOPCC9bgJ2T8TFzAi0NCxQXd4No84bNDDuve4ofod3V29CV9/SNN84BfPhGjoMSJR6NdIb6m2DdE85GDzjRwNPQ+fpiY/XDHax0wIRdi2FSas6XTvFI5sO4gKGAOY00JxVLKhAv0ezGyJArRnfJ8bxNiLpbh0Q8/olB70219z263kNIf0ahQN1O45q7Qg9XGSGnbE9ToTb4r1eQP1Zty4xnxbBSS5pwJ3QHwIdc29iCsgA15dutfFfhsSGYjs/7/zEu92p/D/yzoV0EhbrAqssGS2Bd6NWmn/7QIrwl6JJ8bxuKxhNan7fGIPejdCBfj95O6T8VxMBV9ovJqytUwtXoPZdSAhjm/fXqzKFh3Mm9Q2AqKz6oZgxpCjLWJCQ/EBdgl4VHXNZw7hncv2V5AB4r3X/Qta2OnhbyaH+gasdrs=
  - secure: NIe879uU6zXbHJLNeljBY6Rs5Xi1PZuoZ7lh4ofG/Ofpy39kY9VNzmcyRrjk/iGYLRdB6NTTEoz0reDJjqPyh6l8OcEnMdRnMjK4QiSfjrgI3oQLlpDGwEaB8DBNrnBHmcbgjMYM+CwIgAXwekYL0XXUCIEiCFFrjDVM3C4CcUncRdM1xZXF51x29qpnqirSMwCC6zm6xeusNy/JnWbmQd2gHoxuwkbMkYUcy6XUl2gcasWL9hmjrPkSB6FzY1hN+NP08i1zKokTDw3wxc+VXlN3psaHLXoz0hLPwmNR7SwmgZGfvu6jkQF/1slO29g00AWe8JWej3ns/+pH4pHGVcn8hY+f2FrTgPFazhW6+qLQ1v0eMsIlwRyucxxnzUqibcgje+jUaO2rqCri1M1uYfxP3mrnbMRfrW9yiN0sUnvkZkHTb3ZN8tGB+78BxU/O1Wl+6RFvsZDYGyMaIzt0+bg1e2ucNSpOeWXrZ2zjX3u0U7uoUHlH6GraMgEnqMMsF76eGTbUF3FSJtHO+Ey2Aqyx6zBFTTU/2goibk+nwugAAXUXaeR3kSIjWnyT/qeB2rFj67iNmoCpq2WOHb85Bf5NZvkxntxDAJr5VrWiCBCzyVm3lR6nKCdB4wGnEB47wPQWQXuttAR+p8VYSJ6DEZhMD44iOrrcNSBhKqnm96U=
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: f6A1Ua/Q6pMHyd4oU/V4lMTn03BkU95ol8dygnPkt3HxXP18wm8vLaQDXkAOqmxzR39xbKaiVTJxdNorpuiVS4HEDBjK2ko37mq+t8K14hDMaN4DOoGfXng7dATkLea3bFMo9G98hDaZJq70D7Ka1z3Omn5NSICpVp/co7DzlJnnoGBR9QFHwBBOnRtctKzIX6JbFwTwTFfQCn9cC3td3zT8gan5Zgip9+kBeuRpI3VPO2bPKFPfJ+D9jCDkRMQAcA4ulmsRsgVCv5DuiKv/Z+zwOb1Ds7BWLTQp971h56LSJZ6pZ3Uhd8MUgT3WuGHmqPVYkN1QYwLqCjgGB2KkxHsO8QWaioX4CF2WCwqluSWCtiJIzHNtVb+Gwl8jI5z6GodeRINmoRIt1Ou31Mrjtcjay4c+9gLQ/9KlkKQHukxLLguqQ8k/JSNkS73KozIYtGcTCEpD8bnVab0ZGjuy789mkvVF68/C28uwXpBKUW8vHcfG4A4hxKHyfpOJMtP6QW8097i7ZTWwAPg8SYE3WJMwAFRmRsRvZAM3AolJHxDu2PFiWMQl4RpvlWRZED3do5dvd/aufQevgugMuEO3PQ5Xr8XrAGcHPlWo7+XIPY5cy06LRC+Ryhucxgit8m56i8fsFHlzTZLOvOVi8827h0Qhea0HwVtiIQmTZP6Q8+U=
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=shapeshed/go-ci-cd
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
